### PR TITLE
Add changelog and git guidelines

### PR DESCRIPTION
**Pull request by faern**
Adding guidelines on git and changelogs.

Basically this should be the written form of what we have already agreed on, either explicitly after discussion or implicitly by being something we just do naturally. If the text does not correspond to your current view of things then bring it up and we'll try to reach consensus and alter the text if needed.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @jvff, @pronebird, and @pinkisemils)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGjYD8g7rk3Pg_EqvQu:b-e0xdh3) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
> ```Markdown
>   * _Security_ - in case of vulnerabilities.
> * Add new items to the end of the list of changes under the appropriate category. This way they
>   automatically end up in chronological order within each category.
> ```

I added this to bring up the discussion. I have noticed that @pronebird always adds changes to the top of the list while (I think) everyone else usually add them to the end. This makes it grow in two directions.

Not sure if it's something very important, but it's something I have been noticing and been thinking about. So wanted to see if there is any practical benefit of adding them to the top or just a habit. And if we should continue like that or try to add to the same place.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @jvff, @pronebird, and @pinkisemils)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGj_mDc4fnT-HSGzFXz:boewfru) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I added this to bring up the discussion. I have noticed that @pronebird always adds changes to the top of the list while (I think) everyone else usually add them to the end. This makes it grow in two directions.

Not sure if it's something very important, but it's something I have been noticing and been thinking about. So wanted to see if there is any practical benefit of adding them to the top or just a habit. And if we should continue like that or try to add to the same place.
</blockquote></details>

This is religious mojo, but doesn't it make more sense to look at the top to find out what's new?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @jvff, @pronebird, and @pinkisemils)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGja7Cy5yfv3-xsM7Io:b-wb57u) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is religious mojo, but doesn't it make more sense to look at the top to find out what's new?
</blockquote></details>

"Our top headlines for today! Please flip your paper over and read it backwards" <-- no newspaper, ever

**Comment by jvff** [comment]
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGjaUxj24pOxljXql-O:b-8su40g) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

"Our top headlines for today! Please flip your paper over and read it backwards" <-- no newspaper, ever
</blockquote></details>

But that's about ordering for importance. Not sure if/how we can do that here :/

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

---

*[README.md, line 43 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjaG4l9r8tnh0ZflgD:-LGjaG4l9r8tnh0ZflgE:bgiurte) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L43)):*
> ```Markdown
> experimented to get there.
> 
> So for a given feature branch, each line of code should usually only have to be changed in one
> ```

I would like to bring up something for discussion related to `each line of code should usually only have to be changed in one commit`. I know `usually` here means it depends on the context and is not always possible, but I have a scenario where sometimes it's not possible and I would like the opinion of the group whether the practice in the scenario is useful or not.

Basically as a rule of thumb I try to always have commits that build. I also try to make them pass all tests as well in most of the cases, but that's not always possible. Hence, sometimes to make a commit in the middle of the feature buildable some changes are necessary that would be overwritten in future commits (type changes for example, or changes in function signatures or names).

Is this practice (striving for buildable commits) something you guys find useful? I know it's overkill to have at as a fixed rule, but would it be a useful rule of thumb?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)*

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

___
*[README.md, line 43 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjaG4l9r8tnh0ZflgD:-LGyEpPV2aKqTzRTaU54:b-dq1u79) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L43)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I would like to bring up something for discussion related to `each line of code should usually only have to be changed in one commit`. I know `usually` here means it depends on the context and is not always possible, but I have a scenario where sometimes it's not possible and I would like the opinion of the group whether the practice in the scenario is useful or not.

Basically as a rule of thumb I try to always have commits that build. I also try to make them pass all tests as well in most of the cases, but that's not always possible. Hence, sometimes to make a commit in the middle of the feature buildable some changes are necessary that would be overwritten in future commits (type changes for example, or changes in function signatures or names).

Is this practice (striving for buildable commits) something you guys find useful? I know it's overkill to have at as a fixed rule, but would it be a useful rule of thumb?
</blockquote></details>

Good point. Yes I think buildable at each commit is a good thing to aim for generally. But at the same time with a fairly low priority. What I mean is that I also try to keep each commit buildable if it's a relatively low effort thing to do. But as soon as keeping things buildable require me to do kind of advanced intermediate steps, such as create a type that will just go away later in the branch, then I consider ignoring this noble goal.

There are indeed fully justified situations for changing one line of code multiple times in a single feature branch! So maybe "usually" is a too strong word in the sense that it makes one feel that they should avoid changing something twice even when they already have a good history that changes it more than once.
___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGyGLvn-Dcsu54osLRE:bly136k) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

But that's about ordering for importance. Not sure if/how we can do that here :/
</blockquote></details>

@mvd-ows That builds on the assumption you want to know the very last feature the most. When I compare two versions with their changelog I want to know what changed since that other release. And if the changelog is appended at the end reading it from the start gives me "So, after the `2018.1` release they have first added foo, then fixed bar".

Like when reading the backlog of a chat, you start with what happened directly after last time you were there and work your way forward in time.

But indeed. This is a nitpick point that can be removed all together. As I said I wanted to bring it up and if we all agreed we could keep it, but if we don't we can also just don't have any guideline on the matter.

**Review by mvd-ows — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, @pinkisemils, and @jvff)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LGykIPG8iGicktQ7GH7:b-9pvo1e) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

@mvd-ows That builds on the assumption you want to know the very last feature the most. When I compare two versions with their changelog I want to know what changed since that other release. And if the changelog is appended at the end reading it from the start gives me "So, after the `2018.1` release they have first added foo, then fixed bar".

Like when reading the backlog of a chat, you start with what happened directly after last time you were there and work your way forward in time.

But indeed. This is a nitpick point that can be removed all together. As I said I wanted to bring it up and if we all agreed we could keep it, but if we don't we can also just don't have any guideline on the matter.
</blockquote></details>

I think there should definitely be a guideline. I don't mind what the guideline is.

**Comment by jvff** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

---

*[README.md, line 43 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjaG4l9r8tnh0ZflgD:-LGz-rKH-1RgmzrFgHbY:bpahfia) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Good point. Yes I think buildable at each commit is a good thing to aim for generally. But at the same time with a fairly low priority. What I mean is that I also try to keep each commit buildable if it's a relatively low effort thing to do. But as soon as keeping things buildable require me to do kind of advanced intermediate steps, such as create a type that will just go away later in the branch, then I consider ignoring this noble goal.

There are indeed fully justified situations for changing one line of code multiple times in a single feature branch! So maybe "usually" is a too strong word in the sense that it makes one feel that they should avoid changing something twice even when they already have a good history that changes it more than once.
</blockquote></details>

Understood. Suggestion to reword it: `each line of code should be changed in the least amount of commits as possible`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)*

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @jvff, @pronebird, @pinkisemils, and @faern)

___
*[README.md, line 43 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjaG4l9r8tnh0ZflgD:-LGz6lqJBFQwhiLTbRiH:b-sgices) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L43)):*
In a way that also scare people away from changing it more than once. On a second thought it's not really the number of commits we are trying to limit here by itself. It's the existence of "fix" commits we try to get rid of really, right? So how about this reformulation:
> So for a given feature branch, there should generally not be "fix" commits fixing things from
earlier commits in that same branch.

I pushed that, so see diff for full rewording.

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

---

*[README.md, line 43 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjaG4l9r8tnh0ZflgD:-LGzMSU388dcgmcd_Zv0:bnfp4nl) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

In a way that also scare people away from changing it more than once. On a second thought it's not really the number of commits we are trying to limit here by itself. It's the existence of "fix" commits we try to get rid of really, right? So how about this reformulation:
> So for a given feature branch, there should generally not be "fix" commits fixing things from
earlier commits in that same branch.

I pushed that, so see diff for full rewording.
</blockquote></details>

:lgtm:

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)*

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

**Review by mvd-ows — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pronebird, @pinkisemils, @jvff, and @faern)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LH2m0WdDpejMr1fhSfS:bs3qivu) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I think there should definitely be a guideline. I don't mind what the guideline is.
</blockquote></details>

I don't think the order is important. When I first added a line to the changelog, I thought that the most recent change goes on top. But later on when Linus brought this to my attention, I started appending all new changes to the bottom. I personally do not think it matters much since all changes are released at once with each release.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-:-LH2nVcv3aY_6wNskxVF:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pinkisemils, @jvff, @pronebird, and @faern)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pinkisemils, @jvff, @pronebird, and @faern)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows, @pinkisemils, @jvff, @pronebird, and @faern)

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @jvff, @mvd-ows, @pronebird, and @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/3)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pinkisemils, @jvff, @mvd-ows, and @pronebird)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/3#-LGjYD8g7rk3Pg_EqvQt:-LH2yrZZ4o387bJjDJZu:b-i8mdo5) ([raw file](https://github.com/mullvad/coding-guidelines/blob/04eb2f3b0ffe545f9ed4214bbdcce44ce5c3716f/README.md#L81)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I don't think the order is important. When I first added a line to the changelog, I thought that the most recent change goes on top. But later on when Linus brought this to my attention, I started appending all new changes to the bottom. I personally do not think it matters much since all changes are released at once with each release.
</blockquote></details>

I agree it's on the more nitpicky side. But at least one person wanted it to be an explicit guideline. And if all of us already append at the end it should not be a problem following it really.

**Pull request merged**
