### PR TITLE
Add bash guidelines for parsing arguments

### PR DESCRIPTION
**Pull request by Jontified**
Evaluated getopts and getopt and neither has good cross-platform support for --double-dash flags.
Further reading can be done [here](https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options).

I suggest we go with the `while` loop over the `for` loop because it allows for parsing several arguments in the same iteration which allows us to parse `--flag specific arguments`. I also think the syntax is easy to read and understand.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, @Jontified, and @pinkisemils)

___
*[`bash.md` line 133 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4Bo5Hs98dRckskE_Fc:-N4Bo5Hs98dRckskE_Fd:buvf511) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L133)):*
> ```Markdown
> ## Parsing command-line arguments
> 
> When parsing command-line arguments that have flags use a `while` loop containing a `case` statement that
> ```

"that have flags, use a".
___
*[`bash.md` line 143 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BoMTp0DrQ_i_YWh_1:-N4BoMTp0DrQ_i_YWh_2:b-u18y79) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L143)):*
> ```Markdown
>     case "$1" in
>         "--foo")
>             foo_set="true"
> ```

Since we almost always use `set -u` the variables must be initialized before the parsing begins, otherwise they don't have any default values. I think this fact, how variables filled in by argument parsing should be initialized, is important to declare as part of this guideline chapter.
___
*[`bash.md` line 150 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BnYCd9RIu1xCo_S5i:-N4BnYCe8Egiv6rwNzqx:b4aei4d) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L150)):*
> ```Markdown
>             shift 2
>             ;;
>         -*)
> ```

Do we really need to have separate cases for `-*` and `*`? Feels like it's adding a lot of code for very little value? Does this have any benefit I'm missing? Otherwise I would argue that having the single default case of:
```bash
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
```
Would be enough. Our scripts are usually not that complex or have that many options. So having two fallback cases probably adds a lot of LOC percentage to the parsing :P

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, @Jontified, and @pinkisemils)

___
*[`bash.md` line 133 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BoxOo08dkasp1cCJL:-N4BoxOo08dkasp1cCJM:b-90m03i) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L133)):*
> ```Markdown
> ## Parsing command-line arguments
> 
> When parsing command-line arguments that have flags use a `while` loop containing a `case` statement that
> ```

Please stick to 100 column width. We try to limit most file types to not have lines longer than 100 characters. 

Maybe we should add a `markdown.md` file to this repository where we specify markdown guidelines :P

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[`bash.md` line 133 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4Bo5Hs98dRckskE_Fc:-N4DDZgS9eDZMl0i_PMl:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L133)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"that have flags, use a".
</blockquote></details>

Done.
___
*[`bash.md` line 133 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BoxOo08dkasp1cCJL:-N4DD_sQ0h-QLb4piPJ-:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L133)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please stick to 100 column width. We try to limit most file types to not have lines longer than 100 characters. 

Maybe we should add a `markdown.md` file to this repository where we specify markdown guidelines :P
</blockquote></details>

Done.
___
*[`bash.md` line 143 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BoMTp0DrQ_i_YWh_1:-N4DDavPA5ziS5wyt_En:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L143)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since we almost always use `set -u` the variables must be initialized before the parsing begins, otherwise they don't have any default values. I think this fact, how variables filled in by argument parsing should be initialized, is important to declare as part of this guideline chapter.
</blockquote></details>

Done.
___
*[`bash.md` line 150 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4BnYCd9RIu1xCo_S5i:-N4DDc7X9wmKzcNzeyh9:b-jvi24p) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d12dba001950d4ac5cbee6e9ce0b25f08e1ee29f/bash.md#L150)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we really need to have separate cases for `-*` and `*`? Feels like it's adding a lot of code for very little value? Does this have any benefit I'm missing? Otherwise I would argue that having the single default case of:
```bash
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
```
Would be enough. Our scripts are usually not that complex or have that many options. So having two fallback cases probably adds a lot of LOC percentage to the parsing :P
</blockquote></details>

Done. I don't think it has any significant benefit. The reason for having two different ones would be to differentiate between `-f` and `sometext`, however it seems a bit redundant.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon, @faern, and @pinkisemils)

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, @Jontified, and @pinkisemils)

___
*[`bash.md` line 159 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4WCpqH7h61vT_Edxj-:-N4WCpqH7h61vT_Edxj0:b-6ca75v) ([raw file](https://github.com/mullvad/coding-guidelines/blob/2109a7b65e1765ed4ce854e837ff6e999eecf217/bash.md#L159)):*
> ```Markdown
>             exit 1
>             ;;
>     esac
> ```

This guideline and example is missing a few things.

* How to handle positional arguments, compared to flag arguments. For example like this: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L27
* How to handle mandatory arguments. In other words, not *all* types of arguments need to be initialized before the parsing. In case of a mandatory argument / argument without sane default it can be non-initialized and instead checked after the parsing with `${variable+x}`. Like this: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L32-L36

**Review by pinkisemils — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 3 unresolved discussions (waiting on @Jontified)

___
*[`bash.md` line 144 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9tnQ2ZtoJKBqy1RU:-N4g9tnQ2ZtoJKBqy1RV:b-msadvo) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L144)):*
> ommit

omit
___
*[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4g9ZIkAKAtNbM-kAjr:b-uig7kg) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):*
> ```Markdown
>             shift 2
>             ;;
>         *)
> ```

Should one also handle unrecognized flags (`-*`)? As is done here: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L22

If so, it would probably make sense to fail if there are too many positional arguments as well.

**Comment by Jontified** [comment]
> > Reviewed 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)_ status: all files reviewed, 3 unresolved discussions (waiting on @Jontified)
> 
> _[`bash.md` line 144 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9tnQ2ZtoJKBqy1RU:-N4g9tnQ2ZtoJKBqy1RV:b-msadvo) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L144)):_
> 
> > ommit
> 
> omit

Corrected, thank you.

> _[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4g9ZIkAKAtNbM-kAjr:b-uig7kg) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):_
> 
> > ```gfm
> >             shift 2
> >             ;;
> >         *)
> > ```
> 
> Should one also handle unrecognized flags (`-*`)? As is done here: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L22
> 
> If so, it would probably make sense to fail if there are too many positional arguments as well.

Yes, we should probably specify how to handle unrecognized flags, but why would that impact how many positional arguments are allowed?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4gYp1t7V2nsMST5Kh6:b-7gmkpl) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Yes, we should probably specify how to handle unrecognized flags, but why would that impact how many positional arguments are allowed?
</blockquote></details>

Isn't this what was discussed and removed in the thread just above this one (now closed, you have to expand it)?
___
*[`bash.md` line 141 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gYTaE2xEWJQy89AR4:-N4gYTaE2xEWJQy89AR5:b-pqbfs7) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L141)):*
> ```Markdown
> Because we almost always use `set -u` it is important that all non-mandatory variables
> have been initialized before parsing, otherwise they will not have a default value. In the case
> of mandatory variables it can be checked after the the parsing.
> ```

`the the`
___
*[`bash.md` line 143 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZ37iAGDNUv3Dpgvz:-N4gZ37iAGDNUv3Dpgw-:bx2z6n3) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L143)):*
> ```Markdown
> of mandatory variables it can be checked after the the parsing.
> 
> For positional arguments that are lacking a flag, if there are no other flag arguments then use
> ```

"positional arguments that are lacking a flag"? Positional arguments by definition don't have a flag, no? Flag arguments are never positional afaik. The point of a positional argument is that it is identified by it's position in the argument list (relative other positional arguments, not relative to flags).
___
*[`bash.md` line 169 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZeaW1QYE-psE5kKZ:-N4gZeaW1QYE-psE5kK_:bt2xvt2) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L169)):*
> ```Markdown
>             ;;
>         -*)
>             echo "Unknown option \"$1\""
> ```

I think you will need to create multiple examples instead of cramming all possible scenarios into one. Because I still think we should have a single `*)` failure branch in parse-loops that don't have positional arguments, like how the example was before this last change.

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 7 unresolved discussions (waiting on @faern and @Jontified)

___
*[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4gwSgtB5BEkm1O9Xtn:b-rxq4ud) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):*
> why would that impact how many positional arguments are allowed

It does not impact how flags are handled, but if invalid flags are rejected, shouldn't invalid positional arguments also be rejected? In this example, if you specify four positional args, then the first two are silently dropped. :shrug:

> Isn't this what was discussed and removed in the thread just above this one (now closed, you have to expand it)?

That must have been before positional arguments were added to the example?
___
*[`bash.md` line 165 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gyoRh-_5I4vv-Srwc:-N4gyoRh-_5I4vv-Srwd:b-jjdhjd) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L165)):*
> ```Markdown
>         *)
>             mandatory_positional_arg_1=$1
>             mandatory_positional_arg_2=$2
> ```

Probably nitpicking, but doesn't example this force you to specify positional arguments adjacently to each other?
___
*[`bash.md` line 168 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gvIg47HYon4291zzo:-N4gvIg47HYon4291zzp:bo6j91s) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L168)):*
> ```Markdown
>             shift 1
>             ;;
>         -*)
> ```

This case (`-*`) needs to come before `*`.

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4kiuTM9Z3aNwNk9mOo:buwzz3k) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> why would that impact how many positional arguments are allowed

It does not impact how flags are handled, but if invalid flags are rejected, shouldn't invalid positional arguments also be rejected? In this example, if you specify four positional args, then the first two are silently dropped. :shrug:

> Isn't this what was discussed and removed in the thread just above this one (now closed, you have to expand it)?

That must have been before positional arguments were added to the example?
</blockquote></details>

We decided to remove `-*)` before we started discussing positional arguments, yes. What you are saying makes sense but how do you suggest that we parse positional arguments?
___
*[`bash.md` line 141 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gYTaE2xEWJQy89AR4:-N4kiYWs-TY5KSg6Z7Ne:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L141)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`the the`
</blockquote></details>

Done.
___
*[`bash.md` line 143 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZ37iAGDNUv3Dpgvz:-N4kibP62Yc4w49t_fvk:bhcrx18) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L143)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"positional arguments that are lacking a flag"? Positional arguments by definition don't have a flag, no? Flag arguments are never positional afaik. The point of a positional argument is that it is identified by it's position in the argument list (relative other positional arguments, not relative to flags).
</blockquote></details>

Done. Will remove "that are lacking a flag".
___
*[`bash.md` line 165 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gyoRh-_5I4vv-Srwc:-N4kj8u80vidnQN3Q306:b-1s13py) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L165)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Probably nitpicking, but doesn't example this force you to specify positional arguments adjacently to each other?
</blockquote></details>

Yes it does, I'm not sure how to best suggest people parse their positional arguments. The options I can think of are:
1) They all have to be next to each other and you use `$1`, `$2`, etc to parse them in the same `*)` case.
2) You try to figure out what kind of a positional argument it is inside of `*)` based on what the argument actually is.
3) You only have positional arguments before all flag arguments or after, you use `$1`, `$2`, etc to parse them before the `while` loop and then you shift, or you add a `-gt $nr_positional_arguments` to the loop and parse them after.

It seemed to me that 1) was the easiest to explain and conform to and without having to sacrifice anything except all your positional arguments are next to each other.
___
*[`bash.md` line 168 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gvIg47HYon4291zzo:-N4kkDBi-rS49OYnwbp0:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L168)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This case (`-*`) needs to come before `*`.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`bash.md` line 160 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4l4GuH5OndfbPs3OXA:-N4l4GuI-oBMXGI9ZLQZ:b-21c549) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L160)):*
> ```Markdown
>         "--bar")
>             bar_arg_one=$2
>             bar_arg_two=$3
> ```

A bit nitpicky. But I think it's reasonable to try to avoid `foo` and `bar` and have examples that are more understandable where possible/easy to come up with. Not all, but most examples in this file uses actual from-real-life variable names etc. I think this makes it easier to consume the examples.

How about:
```bash
use_compression="false"
server_ip="127.0.0.1"
server_port="5000"
while ...
    "--compress") use_compression="true";;
    "--server")
        server_ip="$2"
        server_port="$3"
    ....
```
?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`bash.md` line 143 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZ37iAGDNUv3Dpgvz:-N4lO8KK93r7rARE6yfL:bq8na5q) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L143)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done. Will remove "that are lacking a flag".
</blockquote></details>

Maybe reviewable is buggy. But it still is saying "that are lacking a flag" for me.

And the sentence reads strange to me anyway "For positional arguments, if there are no other flag arguments". "Other"? I'd say "For scripts with only positional arguments, just use `$1`, `$2` etc ..."
___
*[`bash.md` line 165 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gyoRh-_5I4vv-Srwc:-N4lOcV2-AaY69g2DgMw:bejrl28) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L165)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Yes it does, I'm not sure how to best suggest people parse their positional arguments. The options I can think of are:
1) They all have to be next to each other and you use `$1`, `$2`, etc to parse them in the same `*)` case.
2) You try to figure out what kind of a positional argument it is inside of `*)` based on what the argument actually is.
3) You only have positional arguments before all flag arguments or after, you use `$1`, `$2`, etc to parse them before the `while` loop and then you shift, or you add a `-gt $nr_positional_arguments` to the loop and parse them after.

It seemed to me that 1) was the easiest to explain and conform to and without having to sacrifice anything except all your positional arguments are next to each other.
</blockquote></details>

4. One could have a separate array of `positional_arguments=()` and append one element to it every time `*)` is hit. And then deal with the array of positional arguments after the while loop.

I'm not saying this is the best solution, but it's a solution. Probably way more complicated than it's worth!

I agree that (1) is probably the most pragmatic approach for our (relatively simple) scripts that we have.

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[`bash.md` line 159 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4WCpqH7h61vT_Edxj-:-N4lVoyl1Fjua95Q19Np:bd3wehi) ([raw file](https://github.com/mullvad/coding-guidelines/blob/2109a7b65e1765ed4ce854e837ff6e999eecf217/bash.md#L159)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This guideline and example is missing a few things.

* How to handle positional arguments, compared to flag arguments. For example like this: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L27
* How to handle mandatory arguments. In other words, not *all* types of arguments need to be initialized before the parsing. In case of a mandatory argument / argument without sane default it can be non-initialized and instead checked after the parsing with `${variable+x}`. Like this: https://github.com/mullvad/mullvadvpn-app/blob/92fa1004440957aa78abc9ca10bfa38a96ce759e/prepare-release.sh#L32-L36
</blockquote></details>

Should have described both of these now.
___
*[`bash.md` line 143 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZ37iAGDNUv3Dpgvz:-N4lVuBQBKavcVBoB7Oa:b-cyhkrr) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L143)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe reviewable is buggy. But it still is saying "that are lacking a flag" for me.

And the sentence reads strange to me anyway "For positional arguments, if there are no other flag arguments". "Other"? I'd say "For scripts with only positional arguments, just use `$1`, `$2` etc ..."
</blockquote></details>

I've rephrased it as requested now.
___
*[`bash.md` line 160 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4l4GuH5OndfbPs3OXA:-N4l9LEpDWT2O3wwO8s1:bbr3dvq) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L160)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

A bit nitpicky. But I think it's reasonable to try to avoid `foo` and `bar` and have examples that are more understandable where possible/easy to come up with. Not all, but most examples in this file uses actual from-real-life variable names etc. I think this makes it easier to consume the examples.

How about:
```bash
use_compression="false"
server_ip="127.0.0.1"
server_port="5000"
while ...
    "--compress") use_compression="true";;
    "--server")
        server_ip="$2"
        server_port="$3"
    ....
```
?
</blockquote></details>

Sounds good. Done.
___
*[`bash.md` line 169 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZeaW1QYE-psE5kKZ:-N4lVayI6M-HiRXR73ME:b-td1h7c) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L169)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think you will need to create multiple examples instead of cramming all possible scenarios into one. Because I still think we should have a single `*)` failure branch in parse-loops that don't have positional arguments, like how the example was before this last change.
</blockquote></details>

Alright, I've added two examples for a total of three. They show: only positional arguments, only flag arguments, both types of arguments.
It might be a bit bloated, if you have suggestions for how to shorten it down let me know.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[`bash.md` line 163 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4g9ZIkAKAtNbM-kAjq:-N4lcUbe2yFCDvEkbg1u:b-9vx6xj) ([raw file](https://github.com/mullvad/coding-guidelines/blob/498668cd5c52adad5673cd9cd8bdf8a11f0a71d9/bash.md#L163)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

We decided to remove `-*)` before we started discussing positional arguments, yes. What you are saying makes sense but how do you suggest that we parse positional arguments?
</blockquote></details>

Answered in another comment.
___
*[`bash.md` line 165 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gyoRh-_5I4vv-Srwc:-N4lcrE09zKGda1h41tK:b-1a2dwd) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L165)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

4. One could have a separate array of `positional_arguments=()` and append one element to it every time `*)` is hit. And then deal with the array of positional arguments after the while loop.

I'm not saying this is the best solution, but it's a solution. Probably way more complicated than it's worth!

I agree that (1) is probably the most pragmatic approach for our (relatively simple) scripts that we have.
</blockquote></details>

(4) is probably the most correct solution, but (1) seems good enough.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`bash.md` line 169 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N4gZeaW1QYE-psE5kKZ:-N50M0ee1dupLCn1TEQF:b-aupyax) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7bc5583dc9b596fea3025f31e963fd1c0c1ff3b1/bash.md#L169)):*
> if you have suggestions for how to shorten it down let me know.

You can simplify the last example. It does not need to show both flags with and without arguments. That is already showcased in the example above. Have the last example have only a flag without argument and the positional arguments.
___
*[`bash.md` line 141 at r5](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N50LE412MZ6kcwdAhbh:-N50LE412MZ6kcwdAhbi:b-9i68c8) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d9c8a1e613c52b359598dbff1ba1e62e30a3cd4e/bash.md#L141)):*
> ```Markdown
> Because we almost always use `set -u` it is important that all non-mandatory variables
> have been initialized before parsing, otherwise they will not have a default value. In the case
> of mandatory variables it can be [checked](Check if variable is defined) after the parsing.
> ```

This markdown link does not work. At least not on github itself. https://github.com/mullvad/coding-guidelines/blob/bash-style-guidelines/bash.md

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`bash.md` line 141 at r5](https://reviewable.io/reviews/mullvad/coding-guidelines/16#-N50LE412MZ6kcwdAhbh:-N50QTxS0RDui57itxeU:bt2vr1b) ([raw file](https://github.com/mullvad/coding-guidelines/blob/d9c8a1e613c52b359598dbff1ba1e62e30a3cd4e/bash.md#L141)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This markdown link does not work. At least not on github itself. https://github.com/mullvad/coding-guidelines/blob/bash-style-guidelines/bash.md
</blockquote></details>

Fixed.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
