### PR TITLE
Add generic file format instructions to main page

### PR DESCRIPTION
**Pull request by faern**
I'm sorry if you think it becomes noisy to review all of these. But the plan is that everyone should have a say when this is created. So hopefully we don't have to change these document very much at all the future, except for adding tips and rules as we reach consensus on more things to follow.

Reason why it's good if we can agree up front and then not having to change them is because a change in these documents likely lead to having to change a lot of code as well. And there will of course be times when that is needed or wanted for various reasons. But the more we can agree up front, the less of those instances we are likely to have I think.

Please remind me if I forgot any small rule we have talked about.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2)

### CODE REVIEW

**Comment by mvd-ows** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @jvff, @pronebird, @pinkisemils, and @mvd-ows)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2)*

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2#-:-LG_BP190mC43VX_ZD2I:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @pronebird, @pinkisemils, @jvff, and @mvd-ows)

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @pinkisemils, @jvff, @mvd-ows, and @pronebird)

**Review by mvd-ows — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2#-:-LGdhsKoAmayVQX5-vp6:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @pinkisemils, @jvff, @mvd-ows, and @pronebird)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
