### PR TITLE
Add initial Bash coding guidelines

### PR DESCRIPTION
**Pull request by faern**
We have a hefty bunch of Bash scripts by now. And the amount of scripts and their complexity grow. But we don't have a uniform standard between them. They vary in style quite a lot depending on who wrote them and when.

This aims to form a standard that all scripts should eventually follow. Meaning once we have agreed on a standard new scripts should be written with this style in mind, and we should slowly update old ones to follow these guidelines.

The guidelines were assembled from a few metrics:
* What we use in most scripts today
* What seems to be good practices to follow to avoid errors and confusion

I submit this as a draft PR and let a few review it. If they approve (after possibly modifying it) we'll let everyone chip in. So we have consensus before anything is merged or any existing scripts are updated.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dlon and @raksooo)

**Review by raksooo — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dlon, @mvd-ows, @pinkisemils, and @raksooo)

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[bash.md, line 35 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M2-rkLzCfZkrXfaaGLs:-M2-rkM0AV833mceu2G2:bw2t8nj) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L35)):*
> ```Markdown
> ```
> 
> The above is the most cross platform way of obtaining the directory of the script.
> ```

I recall there's a way to register a function to be executed as the script is about to exit. Would it not be useful to restore the former working directory?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[bash.md, line 35 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M2-rkLzCfZkrXfaaGLs:-M23mDAxBThanYlZyrdO:b-55g31j) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L35)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I recall there's a way to register a function to be executed as the script is about to exit. Would it not be useful to restore the former working directory?
</blockquote></details>

A `cd` in a script does not change the working directory for the parent shell that executes said script. All our scripts already have a bunch of `cd`s. For example `cd "$SCRIPT_DIR"` at the start of almost every script. They don't screw up the parent shell.

**Review by mvd-ows — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dlon, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 35 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M2-rkLzCfZkrXfaaGLs:-M25128f72A88ex6IlDL:bwcc1gv) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

A `cd` in a script does not change the working directory for the parent shell that executes said script. All our scripts already have a bunch of `cd`s. For example `cd "$SCRIPT_DIR"` at the start of almost every script. They don't screw up the parent shell.
</blockquote></details>

Ah, right. good stuff.

**Review by jvff — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 28 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M24vR8I7aS8qQTG16PK:-M24vR8J8pGDd7Gptqb8:b-1bg7q6) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L28)):*
> ```Markdown
> If a script uses relative paths the current working directory can affect the outcome in
> undesirable ways. To mitigate this start the script by computing the path to the script
> and cd to it:
> ```

Nit: Maybe place `cd` between quotes to highlight it as a command?
___
*[bash.md, line 122 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M25HX1c6LgMCj1RcZQ9:-M25HX1e9Bix4Q4YAc1B:b-2ng3o5) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L122)):*
> ```Markdown
>     clear_tmp $log_filename
> done
> ```
> ```

Nit: Just to bring this up in case it wasn't mentioned before, but is this file missing an ending newline, or is this Reviewable acting strange?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dlon, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 28 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M24vR8I7aS8qQTG16PK:-M25PM8C6DRa2M-COQc_:bt2vr1b) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Maybe place `cd` between quotes to highlight it as a command?
</blockquote></details>

Fixed.
___
*[bash.md, line 122 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M25HX1c6LgMCj1RcZQ9:-M25PPM93RCYRqdjfQZ4:bt2vr1b) ([raw file](https://github.com/mullvad/coding-guidelines/blob/fd406cb31fe29dcbe8e35df932efd690f0cae1f0/bash.md#L122)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Just to bring this up in case it wasn't mentioned before, but is this file missing an ending newline, or is this Reviewable acting strange?
</blockquote></details>

Fixed.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 48 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M28WlS06f0GVg_DoaxK:-M28WlS06f0GVg_DoaxL:b-u0ns04) ([raw file](https://github.com/mullvad/coding-guidelines/blob/e3065465dda3b0ccf8f75a0e3d664dfd47bd115b/bash.md#L48)):*
> ```Markdown
> 
> * Non-constant variables use `snake_case` names.
> ```

If that's a list of items, then a double space is missing on this line to include the paragraph below into the list item.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 8 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M28XkSiEOZZudBqMXpo:-M28XkSiEOZZudBqMXpp:b-5n5wsz) ([raw file](https://github.com/mullvad/coding-guidelines/blob/e3065465dda3b0ccf8f75a0e3d664dfd47bd115b/bash.md#L8)):*
> ```Markdown
> Without it it might be ran by either `bash` or `sh` depending on the environment,
> and the outcome might be different.
> ```bash
> ```

Nit: it wouldn't hurt to add the extra newline between the code block and paragraph. It makes it easier to read the markdown source and AFAIK has no impact on the rendered HTML.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

___
*[bash.md, line 61 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M28Y2y11_Fs2wUgmchS:-M28Y2y11_Fs2wUgmchT:b-yw9a0w) ([raw file](https://github.com/mullvad/coding-guidelines/blob/e3065465dda3b0ccf8f75a0e3d664dfd47bd115b/bash.md#L61)):*
> ```Markdown
> (They most likely should not be). This stops execution of functions from polluting the global
> namespace. Do this both for constants and other variables.
> ```bash
> ```

Nit: same here, could be better to have an extra newline to separate the paragraph from the code block

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[bash.md, line 48 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M28WlS06f0GVg_DoaxK:-M29AbvQ-Whz5MHKY0ia:b3pxzdh) ([raw file](https://github.com/mullvad/coding-guidelines/blob/e3065465dda3b0ccf8f75a0e3d664dfd47bd115b/bash.md#L48)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

If that's a list of items, then a double space is missing on this line to include the paragraph below into the list item.
</blockquote></details>

It already renders well on github: https://github.com/mullvad/coding-guidelines/blob/add-bash-guide/bash.md#constants-vs-other-variables . And it renders equally well in VSCode for me. So not sure which renderer need those two spaces.

Since I'm not a fan of trailing spaces I instead removed the ones from the bullet point above to be consistent. Tell me if this causes rendering issues anywhere where we care about.

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

___
*[bash.md, line 42 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M29Bwc437DBHX7lT6bQ:-M29Bwc5BzgQ5Zc8Pmk8:brkba21) ([raw file](https://github.com/mullvad/coding-guidelines/blob/51f120763817bd3fb9df33db235f17bea18acf16/bash.md#L42)):*
> ```Markdown
> ### Constants vs other variables
> 
> * Constant variables use `SCREAMING_SNAKE_CASE` names
> ```

Nit: Just pointing it out in case it's a mistake: the period was removed here. Not sure if it should be removed on the other list item or if it should be restored.

**Review by pinkisemils — APPROVED** [review]
Would it make sense to try and use [shellcheck](https://github.com/koalaman/shellcheck) to enforce some of these guidelines?

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-:-M2AYDq1DOCYa-8lpBwl:b-jq7fhg)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

**Review by faern — COMMENTED** [review]
I don't think we should add it as a requirement now since many of our existing scripts break our own guidelines in one or many ways. But I can add it as a tip, something people are encouraged to use to find flaws and improve their code quality. In some bright future when we have fixed all existing scripts maybe we can add it as a requirement in some way?

I added a section about it. Do you think this is good for now?

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-:-M2JQ9f513enSB88FktG:b-iil9ie)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jvff and @pronebird)

**Review by pinkisemils — APPROVED** [review]
I think it'll be good enough for now :thumbsup: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-:-M2JRz_57_-U8LYHKiga:b69ktjv)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Comment by jvff** [comment]
___
*[bash.md, line 7 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M2JS3K1CQXQdy2UnDa5:-M2JS3K1CQXQdy2UnDa6:bg3u69p) ([raw file](https://github.com/mullvad/coding-guidelines/blob/c28d48b21e98fd958d5b16361b4f81a5f7ac4afc/bash.md#L7)):*
> ```Markdown
> nice code.
> 
> [`shellsheck`]: https://www.shellcheck.net/
> ```

Is there a typo here somewhere? Haven't checked if it's `shellcheck` or `shellsheck`

**Comment by jvff** [comment]
___
*[bash.md, line 7 at r4](https://reviewable.io/reviews/mullvad/coding-guidelines/5#-M2JS3K1CQXQdy2UnDa5:-M2JSB0rEtALvSWOWvd3:b-e7l0uk) ([raw file](https://github.com/mullvad/coding-guidelines/blob/c28d48b21e98fd958d5b16361b4f81a5f7ac4afc/bash.md#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is there a typo here somewhere? Haven't checked if it's `shellcheck` or `shellsheck`
</blockquote></details>

It seems it's `shellcheck`, so I think the URL is correct, but the not the text.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/5)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

**Pull request merged**
