### PR TITLE
Add section on converting between types in Rust

### PR DESCRIPTION
**Pull request by faern**
These are some guidelines I have been advocating for for a long time. But they have never been written down. I felt like now was a good time to see what your opinion on the matter is, and actually introduce it to our guidelines.

As with most guideline changes, all affected parties are tagged as reviewers. It's important that we agree and are aware of the coding guidelines.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/14)

### CODE REVIEW

**Review by Jontified — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/14)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon, @Jontified, and @pinkisemils)

**Review by Jontified — APPROVED** [review]
Looks good to me.

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/14#-:-N3x7SnjAeyEoj7SVxLe:b9j9n43)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon, @Jontified, and @pinkisemils)

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/14)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Jontified and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
