### PR TITLE
Add guidelines about co-authored commits

### PR DESCRIPTION
**Pull request by dlon**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
Great addition!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-NznssWA9kWPDQDFyxAc:b2sguml)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @dlon, @faern, @pinkisemils, and @raksooo)

___
*[`README.md` line 233 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-Nznt0zS9AfMknBs0EG-:-Nznt0zS9AfMknBs0EG0:b-1fpcsr) ([raw file](https://github.com/mullvad/coding-guidelines/blob/bd50db2dd8b2a6cbe987382afbab5f25cfeb5a03/README.md#L233)):*
nit:  I believe these lines should also be prefixed with `> `, but might also depend on the shell.

```
> Co-authored-by: ...
```



_Code quote:_
```Markdown
Co-authored-by: Name 1 <name1@example.com>
Co-authored-by: Name 2 <name2@example.com>"
```

**Review by pinkisemils — COMMENTED** [review]
Is this something we should be doing manually? Is this something we *must* do or this just a suggestion?

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-0ZeJQAERnV17iOs7M:brjvlwx)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @dlon, @faern, and @raksooo)

**Review by dlon — COMMENTED** [review]
> Is this something we _must_ do or this just a suggestion?

It probably should be done for changes that are significant. But I can demote this to a suggestion if it's too much overhead.

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-0oS0mDVG2ZxMYopkb:b5mwhxx)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @faern, and @raksooo)

**Review by albin-mullvad — COMMENTED** [review]
Yeah, makes sense to use for significant changes, but we probably shouldn't require it for minor changes

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-0y62b93n8_zzbY5vw:b-8hblex)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @dlon, @faern, and @raksooo)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @raksooo)

___
*[`README.md` line 233 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-Nznt0zS9AfMknBs0EG-:-O-1Q8-iD5_7KNPymyS-:b-5co8z7) ([raw file](https://github.com/mullvad/coding-guidelines/blob/bd50db2dd8b2a6cbe987382afbab5f25cfeb5a03/README.md#L233)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit:  I believe these lines should also be prefixed with `> `, but might also depend on the shell.

```
> Co-authored-by: ...
```
</blockquote></details>

I removed both `>` instead.

**Review by faern — APPROVED** [review]
I agree it should not be a requirement. It should not be mandatory bureaucracy, but rather an optional way of sharing credit.
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-5I2Lf6ewrRI321mdY:bohxlyo)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @raksooo)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-8ORNf1Cj_ltFNfLvx:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @raksooo)

___
*[`README.md` line 233 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-Nznt0zS9AfMknBs0EG-:-O-8OM7i1oswZ6j0F4NG:b4c9lyr) ([raw file](https://github.com/mullvad/coding-guidelines/blob/bd50db2dd8b2a6cbe987382afbab5f25cfeb5a03/README.md#L233)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I removed both `>` instead.
</blockquote></details>

:thumbsup:

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23#-:-O-Ku-mF6dVaD9F2V_bO:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @raksooo)

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/23)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @raksooo)

**Pull request merged**
