### PR TITLE
Add sections about code quality, documentation and limiting complexity

### PR DESCRIPTION
**Pull request by faern**
Adding a few sections about how to reason about code quality, limiting the scope of a task and what to document.

A lot of this we talk about internally now and then. But it's not really written down. I want to make it more clear that we value quality over speed and that you should take the time to produce something you are proud over rather than whatever can get merged the fastest.

Better ways of writing this? What more should I mention?

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
I assigned the rest of the team since it involves changes to coding guidelines. I find it better that you read this and give feedback/approve of it now rather than later. If I did not assign you I would have to make everyone read it after it's merged (because all developers should be aware of the guidelines) so this felt like a smoother way of having everyone read it up front.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @dlon, @mvd-ows, @pinkisemils, @pronebird, and @raksooo)

**Review by mvd-ows — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @dlon, @pinkisemils, @pronebird, and @raksooo)

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @dlon, @pinkisemils, @pronebird, and @raksooo)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @dlon, @pinkisemils, @pronebird, and @raksooo)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @dlon, @pinkisemils, @pronebird, and @raksooo)

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
